### ISSUE TITLE
Регистр имени файла не соответствует регистру при импорте

### ISSUE THREAD

**Issue by vladimixz** [Igonko/Onix-Internship#5]
https://prnt.sc/10188x5

**Comment by Igonko** [comment]
Исправлено, переименовывал все компоненты с большой буквы.

**Comment by vladimixz** [comment]
![image](https://user-images.githubusercontent.com/8568965/111000996-b4168680-838b-11eb-920c-ad3e00f420dd.png)
проблема актуальна, смотрел на последней версии ветки main

**Comment by Igonko** [comment]
исправлено, помогло удаление комит/пуш и возврат файла.
