### ISSUE TITLE
Пути к компонентам

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Igonko/Onix-Internship#7]
Приложение не будет работать на других ОС из-за того что большенство из них в отличии от windows регистрозависимые, а значит большая и маленькие будет отличаются. Лучше всего если название всех файлов с компонентами будет с большой буквы, так же как и папки в которых эти компоненты. И в импорте компонентов эти названия тоже должны бить с большой буквы

**Comment by Igonko** [comment]
Локально все проставлено с большой буквы, папки и названия компонентов. В гит не заливает как проставлено.

**Comment by Igonko** [comment]
Перезалил весь проэкт предварительно удалив все компоненты. Вопрос исправлен.
